name: Deploy Svelte to GitHub Pages

on:
  push:
  workflow_dispatch:

# (*・∀-)ｂ
# (o^∀^)
# ＼(≧U≦）/
#

env:
  output-branch: pages
  output-dir: public
  commit-message: ＼(≧U≦）/ update
  remote: https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git

jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Compile Svelte
        run: |
          npm install -f
          npm run build

      - name: Push to ${{ env.output-branch }}
        run: |
          cd ${{ env.output-dir }}
          git init
          git config --global user.email "support+actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global init.defaultBranch master
          git remote add origin ${{ env.remote }}
          git checkout -b ${{ env.output-branch }}
          git add .
          git commit -m "${{ env.commit-message }}"
          git push -u origin ${{ env.output-branch }} -f
